#!/bin/bash -l

# Set SCC project
#$ -P mcnet

# Specify hard time limit for the job.
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=48:00:00

# Send an email when the job finishes or if it is aborted (by default no email is sent).
####$ -m ea

# Give job a name
#$ -N put_lastObjOnly_codellama13b_n200

# Combine output and error files into a single file
#$ -j y
#$ -o log-put-lastobjonly-new

# request 6 cores, each with 6 GB RAM at least
#$ -pe omp 4
###$ -l mem_per_core=6G

# request 1 GPU
#$ -l gpus=1
#$ -l gpu_c=8.5
#####$ -l gpu_type=V100
#$ -l gpu_memory=47G

# Submit an array job with 5 tasks
#$ -t 1

# Keep track of information related to the current job
echo "=========================================================="
echo "Start date : $(date)"
echo "Job name : $JOB_NAME"
echo "Job ID : $JOB_ID  $SGE_TASK_ID"
echo "=========================================================="
nvidia-smi

module load cuda/11.8
module load torch/2.1
module load miniconda/23.11.0
conda activate <your_env>

# API keys and caching dirs
export HF_HOME="<your hf home>"
export HF_TOKEN="<your hf token>"
ROOT=$(pwd)
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

index=$(($SGE_TASK_ID-1))

MODEL="codellama/CodeLlama-13b-hf"
MODEL_NAME="codellama-13b"

cd nnsight_patching_experiments
# CUDA_LAUNCH_BLOCKING=1 TORCH_USE_CUDA_DSA=true

CUDA_LAUNCH_BLOCKING=1 TORCH_USE_CUDA_DSA=true python run_path_patching.py \
  --model $MODEL \
  --datafile "${ROOT}/data/boxes_altAlways_1put_moreObj_noEmpty/train-t5.jsonl" \
  --batch_size 4 \
  --num_samples 200 \
  --ops_order "put" \
  --query_ops_order "put" \
  --output_dir "${ROOT}/outputs/nnsight_patch_1put/${MODEL_NAME}/logp_lastObjOnly" \
  --counterfactual "rand_obj_rand_query_id" \
  --success_filter true \
  --sort_query_objects \
  --num_query_object 2 \
  --score_source logp \
  --use_object_index "-1" \
  --load_in_8bit


